services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: san-app
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Port=3306;Database=san;Uid=root;Pwd=1234;"
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "17276:17276"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-kontener
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: san
    ports:
      - "3306:3306"
    volumes:
      - mysql_dane:/var/lib/mysql
      - ./san.sql:/docker-entrypoint-initdb.d/san.sql

volumes:
  mysql_dane:
